apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api
  labels:
    app: fast-api
  annotations:
    teste: teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
      - name: fast-api
        image: diogoneiss/cloud-computing:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /api-data
            name: api-volume
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 400Mi
        env:
          - name: VERSION
            value: "V1.0"
          - name: BASE_DIR
            value: /api-data
          - name: PICKLE_DIR
            value: /pickles
          - name: RECOMMENDATIONS_FILE
            value: recommendations.pickle
          - name: BEST_TRACKS_FILE
            value: best_tracks.pickle
          - name: DATA_INVALIDATION_FILE
            value: last_execution.txt
          - name: K_BEST_TRACKS
            value: "10"
          - name: POLLING_WAIT_IN_MINUTES
            value: "5"
          - name: CACHE_BUSTER
            value: "1"
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: fast-api-claim