apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job-3
  labels:
    jobgroup: ml-job
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: ml-job
    spec:
      containers:
      - name: machine-learning-service
        image: diogoneiss/machine-learning-service:latest
        volumeMounts:
          - mountPath: /api-data
            name: api-volume
        env:
          - name: BASE_DIR
            value: /api-data
          - name: DATASETS_DIR
            value: ./datasets
          - name: REGEX_FILENAME
            value: 2023_spotify_ds*.csv
          - name: MIN_SUPPORT
            value: "0.05"
      restartPolicy: OnFailure
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: fast-api-claim