apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job-2
  labels:
    jobgroup: ml-job
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: ml-job
    spec:
      containers:
      - name: machine-learning-service
        image: diogoneiss/machine-learning-service:latest
        volumeMounts:
          - mountPath: /api-data
            name: api-volume
      restartPolicy: OnFailure
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: fast-api-claim