apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job-7
  labels:
    jobgroup: ml-job
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  ttlSecondsAfterFinished: 1200
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: ml-job
    spec:
      containers:
      - name: machine-learning-service
        image: diogoneiss/machine-learning-service:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /api-data
            name: api-volume
        env:
          - name: BASE_DIR
            value: /api-data
          - name: DATASETS_DIR
            value: /api-data/datasets
          - name: REGEX_FILENAME
            value: 2023_spotify_ds*.csv
          - name: MIN_SUPPORT
            value: "0.05"
          - name: RECOMMENDATIONS_FILE
            value: recommendations.pickle
          - name: BEST_TRACKS_FILE
            value: best_tracks.pickle
          - name: DATA_INVALIDATION_FILE
            value: last_execution.txt
          - name: TOP_TRACKS_SAVE_PERCENTILE
            value: "0.03"
      restartPolicy: OnFailure
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: fast-api-claim