apiVersion: v1
kind: Service
metadata:
  name: fast-api
spec:
  type: NodePort
  selector:
    app: fast-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  # type: LoadBalancer